### ISSUE TITLE
stereochemistry no depicted

### ISSUE THREAD

**Issue by egonw** [bioclipse/bioclipse.cheminformatics#55]
Code to reproduce:

```
ui.open(cdk.fromSMILES("N[C@@H](CCS)C(O)=O"))
```

Output does not show a wedge bond (neither editor nor the 2D view):

![image](https://cloud.githubusercontent.com/assets/26721/18806547/bd0fa688-8230-11e6-8ead-394b52701ddb.png)

**Comment by goglepox** [comment]
Fixed in 2.7.0 RC1
